### ISSUE TITLE
Using static credentials 

### ISSUE THREAD

**Issue by gareth326771** [solidusio/solidus_stripe#52]
Hello,

I was asked to leave this issue by Peter as encountered a problem using the static credentials for this gem.

Docs all followed, set to use 'stripe_env_credentials' in the admin panel, with the following set in `config/initializers/spree` :

```
  config.static_model_preferences.add(
    Spree::PaymentMethod::StripeCreditCard,
    'stripe_env_credentials',
    secret_key: ENV['STRIPE_SECRET_KEY'],
    publishable_key: ENV['STRIPE_PUBLISHABLE_KEY'],
    stripe_country: 'US',
    v3_elements: false,
    v3_intents: false,
    server: Rails.env.production? ? 'production' : 'test',
    test_mode: !Rails.env.production?
  )
end

```
Gives this error when I try to pay using Stripe test card in development:

```
ArgumentError in Spree::CheckoutController#update
Missing required parameter: login
```

Error output:

```
            raise ArgumentError.new("Parameter: #{param.first} must be one of #{valid_options.to_sentence(words_connector: 'or')}") unless valid_options.include?(hash[param.first])
          else
            raise ArgumentError.new("Missing required parameter: #{param}") unless hash.has_key?(param)
          end
        end
      end
```
Works fine when creds are set in the admin panel...

Hope this helps, let me know if you need more info.

**Comment by kennyadsl** [comment]
Hey there, do you have a full backtrace of that error to share? Also, which version of Solidus are you using?

**Comment by gareth326771** [comment]
Sure, its Solidus 2.10 see below and let me know if you need anything else.

```
activemerchant (1.107.1) lib/active_merchant/billing/gateway.rb:325:in `block in requires!'
activemerchant (1.107.1) lib/active_merchant/billing/gateway.rb:318:in `each'
activemerchant (1.107.1) lib/active_merchant/billing/gateway.rb:318:in `requires!'
activemerchant (1.107.1) lib/active_merchant/billing/gateways/stripe.rb:76:in `initialize'
solidus_core (2.10.0) app/models/spree/payment_method.rb:140:in `new'
solidus_core (2.10.0) app/models/spree/payment_method.rb:140:in `gateway'
solidus_stripe (3.2.0) app/models/spree/payment_method/stripe_credit_card.rb:107:in `create_profile'
solidus_core (2.10.0) app/models/spree/payment.rb:197:in `create_payment_profile'
activesupport (5.2.4.2) lib/active_support/callbacks.rb:426:in `block in make_lambda'
activesupport (5.2.4.2) lib/active_support/callbacks.rb:236:in `block in halting_and_conditional'
activesupport (5.2.4.2) lib/active_support/callbacks.rb:517:in `block in invoke_after'
activesupport (5.2.4.2) lib/active_support/callbacks.rb:517:in `each'
activesupport (5.2.4.2) lib/active_support/callbacks.rb:517:in `invoke_after'
activesupport (5.2.4.2) lib/active_support/callbacks.rb:133:in `run_callbacks'
activesupport (5.2.4.2) lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
activerecord (5.2.4.2) lib/active_record/callbacks.rb:342:in `create_or_update'
activerecord (5.2.4.2) lib/active_record/persistence.rb:275:in `save'
activerecord (5.2.4.2) lib/active_record/validations.rb:46:in `save'
activerecord (5.2.4.2) lib/active_record/transactions.rb:310:in `block (2 levels) in save'
activerecord (5.2.4.2) lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
activerecord (5.2.4.2) lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
activerecord (5.2.4.2) lib/active_record/transactions.rb:212:in `transaction'
activerecord (5.2.4.2) lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
activerecord (5.2.4.2) lib/active_record/transactions.rb:310:in `block in save'
activerecord (5.2.4.2) lib/active_record/transactions.rb:325:in `rollback_active_record_state!'
activerecord (5.2.4.2) lib/active_record/transactions.rb:309:in `save'
activerecord (5.2.4.2) lib/active_record/suppressor.rb:44:in `save'
state_machines-activerecord (0.6.0) lib/state_machines/integrations/active_record.rb:511:in `block in save'
state_machines-activerecord (0.6.0) lib/state_machines/integrations/active_record.rb:530:in `block in around_save'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:150:in `block in run_actions'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:170:in `catch_exceptions'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:148:in `run_actions'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:133:in `run_callbacks'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:212:in `run_callbacks'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:63:in `block (2 levels) in perform'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:63:in `catch'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:63:in `block in perform'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:186:in `within_transaction'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:62:in `perform'
state_machines-activerecord (0.6.0) lib/state_machines/integrations/active_record.rb:530:in `around_save'
state_machines-activerecord (0.6.0) lib/state_machines/integrations/active_record.rb:511:in `save'
activerecord (5.2.4.2) lib/active_record/associations/collection_association.rb:377:in `insert_record'
activerecord (5.2.4.2) lib/active_record/associations/has_many_association.rb:36:in `insert_record'
activerecord (5.2.4.2) lib/active_record/autosave_association.rb:406:in `block in save_collection_association'
activerecord (5.2.4.2) lib/active_record/autosave_association.rb:399:in `each'
activerecord (5.2.4.2) lib/active_record/autosave_association.rb:399:in `save_collection_association'
activerecord (5.2.4.2) lib/active_record/autosave_association.rb:187:in `block in add_autosave_association_callbacks'
activerecord (5.2.4.2) lib/active_record/autosave_association.rb:159:in `instance_eval'
activerecord (5.2.4.2) lib/active_record/autosave_association.rb:159:in `block in define_non_cyclic_method'
activesupport (5.2.4.2) lib/active_support/callbacks.rb:426:in `block in make_lambda'
activesupport (5.2.4.2) lib/active_support/callbacks.rb:236:in `block in halting_and_conditional'
activesupport (5.2.4.2) lib/active_support/callbacks.rb:517:in `block in invoke_after'
activesupport (5.2.4.2) lib/active_support/callbacks.rb:517:in `each'
activesupport (5.2.4.2) lib/active_support/callbacks.rb:517:in `invoke_after'
activesupport (5.2.4.2) lib/active_support/callbacks.rb:133:in `run_callbacks'
activesupport (5.2.4.2) lib/active_support/callbacks.rb:816:in `_run_update_callbacks'
activerecord (5.2.4.2) lib/active_record/callbacks.rb:350:in `_update_record'
activerecord (5.2.4.2) lib/active_record/timestamp.rb:114:in `_update_record'
activerecord (5.2.4.2) lib/active_record/persistence.rb:705:in `create_or_update'
activerecord (5.2.4.2) lib/active_record/callbacks.rb:342:in `block in create_or_update'
activesupport (5.2.4.2) lib/active_support/callbacks.rb:132:in `run_callbacks'
activesupport (5.2.4.2) lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
activerecord (5.2.4.2) lib/active_record/callbacks.rb:342:in `create_or_update'
activerecord (5.2.4.2) lib/active_record/persistence.rb:275:in `save'
activerecord (5.2.4.2) lib/active_record/validations.rb:46:in `save'
activerecord (5.2.4.2) lib/active_record/transactions.rb:310:in `block (2 levels) in save'
activerecord (5.2.4.2) lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
activerecord (5.2.4.2) lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
activerecord (5.2.4.2) lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/Users/garethphillips/.rbenv/versions/2.4.5/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
activerecord (5.2.4.2) lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
activerecord (5.2.4.2) lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
activerecord (5.2.4.2) lib/active_record/transactions.rb:212:in `transaction'
activerecord (5.2.4.2) lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
activerecord (5.2.4.2) lib/active_record/transactions.rb:310:in `block in save'
activerecord (5.2.4.2) lib/active_record/transactions.rb:325:in `rollback_active_record_state!'
activerecord (5.2.4.2) lib/active_record/transactions.rb:309:in `save'
activerecord (5.2.4.2) lib/active_record/suppressor.rb:44:in `save'
state_machines-activerecord (0.6.0) lib/state_machines/integrations/active_record.rb:511:in `block in save'
state_machines-activerecord (0.6.0) lib/state_machines/integrations/active_record.rb:530:in `block in around_save'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:150:in `block in run_actions'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:170:in `catch_exceptions'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:148:in `run_actions'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:133:in `run_callbacks'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:212:in `run_callbacks'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:63:in `block (2 levels) in perform'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:63:in `catch'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:63:in `block in perform'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:186:in `within_transaction'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:62:in `perform'
state_machines-activerecord (0.6.0) lib/state_machines/integrations/active_record.rb:530:in `around_save'
state_machines-activerecord (0.6.0) lib/state_machines/integrations/active_record.rb:511:in `save'
solidus_core (2.10.0) app/models/spree/order_update_attributes.rb:24:in `apply'
solidus_frontend (2.10.0) app/controllers/spree/checkout_controller.rb:54:in `update_order'
solidus_frontend (2.10.0) app/controllers/spree/checkout_controller.rb:31:in `update'
actionpack (5.2.4.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.4.2) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.4.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.4.2) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.4.2) lib/active_support/callbacks.rb:109:in `block in run_callbacks'
solidus_frontend (2.10.0) app/controllers/spree/store_controller.rb:24:in `block in lock_order'
solidus_core (2.10.0) app/models/spree/order_mutex.rb:29:in `with_lock!'
solidus_frontend (2.10.0) app/controllers/spree/store_controller.rb:24:in `lock_order'
activesupport (5.2.4.2) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
activesupport (5.2.4.2) lib/active_support/callbacks.rb:136:in `run_callbacks'
actionpack (5.2.4.2) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.4.2) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.4.2) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.4.2) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.4.2) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.4.2) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.4.2) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.4.2) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.4.2) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.4.2) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.4.2) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.4.2) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.4.2) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.4.2) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.4.2) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.4.2) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.4.2) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.4.2) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.4.2) lib/action_dispatch/routing/route_set.rb:840:in `call'
railties (5.2.4.2) lib/rails/engine.rb:524:in `call'
railties (5.2.4.2) lib/rails/railtie.rb:190:in `public_send'
railties (5.2.4.2) lib/rails/railtie.rb:190:in `method_missing'
actionpack (5.2.4.2) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (5.2.4.2) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (5.2.4.2) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.4.2) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.4.2) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.4.2) lib/action_dispatch/routing/route_set.rb:840:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.2.2) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.2) lib/rack/etag.rb:27:in `call'
rack (2.2.2) lib/rack/conditional_get.rb:40:in `call'
rack (2.2.2) lib/rack/head.rb:12:in `call'
actionpack (5.2.4.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.2) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.2) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.4.2) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.4.2) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.4.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.4.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.4.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.4.2) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.4.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.4.2) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.4.2) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.2) lib/rack/method_override.rb:24:in `call'
rack (2.2.2) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.4.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.2) lib/rack/sendfile.rb:110:in `call'
railties (5.2.4.2) lib/rails/engine.rb:524:in `call'
puma (3.12.4) lib/puma/configuration.rb:227:in `call'
puma (3.12.4) lib/puma/server.rb:675:in `handle_request'
puma (3.12.4) lib/puma/server.rb:476:in `process_client'
puma (3.12.4) lib/puma/server.rb:334:in `block in run'
puma (3.12.4) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

**Comment by kennyadsl** [comment]
I'm taking a look and it seems that we are passing the login option to ActiveMerchant [here](https://github.com/solidusio/solidus_stripe/blob/master/app/models/spree/payment_method/stripe_credit_card.rb#L93). Maybe we just don't have the `ENV['STRIPE_SECRET_KEY']` env variable set?

**Comment by gareth326771** [comment]
Here is the config file -

```
  config.static_model_preferences.add(
    Spree::PaymentMethod::StripeCreditCard,
    'stripe_env_credentials',
    secret_key: ENV['STRIPE_SECRET_KEY'],
    publishable_key: ENV['STRIPE_PUBLISHABLE_KEY'],
    stripe_country: 'US',
    v3_elements: false,
    v3_intents: false,
    server: Rails.env.production? ? 'production' : 'test',
    test_mode: !Rails.env.production?
  )
```

I have tried hard coding it in there too and that hit the same issue.... I just double checked the key is right (and it was working using the custom selector / admin panel without the v3 selected).

Will test it now again to make sure.

**Comment by gareth326771** [comment]
This was a problem my end with the ENV variables not being passed properly to the config file! Thanks for assistance Solidus team.
