### ISSUE TITLE
Payment Intent creation exception handling with class not present in the gem

### ISSUE THREAD

**Issue by rainerdema** [solidusio/solidus_stripe#55]
After updating the `solidus_stripe` gem and writing some tests, I had some problems with exception handling during the creation of an intent payment.
In `SolidusStripe::IntentsController`:

https://github.com/solidusio/solidus_stripe/blob/9894cddd22c838af399a034eec7dbd7230b1e7e2/app/controllers/solidus_stripe/intents_controller.rb#L7-L16

The [`Stripe::CardError`](https://github.com/stripe/stripe-ruby/blob/1a20c2476d35d80e411e5a692727ed5438614d66/lib/stripe/errors.rb#L75-L85) class is an integral part of the [`stripe-ruby`](https://github.com/stripe/stripe-ruby) gem, which I don't find included here.

From a first analysis, it seems that it's the only point where a `stripe-ruby` class is used.

**Workaround**

To overcome this problem, I merely momentarily included the gem in the project.

**Additional context**

<details>
  <summary>Exception backtrace</summary>
  
  ```ruby
NameError (uninitialized constant SolidusStripe::IntentsController::Stripe):

solidus_stripe (4.0.0) app/controllers/solidus_stripe/intents_controller.rb:10:in `rescue in create_intent'
solidus_stripe (4.0.0) app/controllers/solidus_stripe/intents_controller.rb:8:in `create_intent'
actionpack (5.2.4.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.4.2) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.4.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.4.2) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.4.2) lib/active_support/callbacks.rb:132:in `run_callbacks'
actionpack (5.2.4.2) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.4.2) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.4.2) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.4.2) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.4.2) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.4.2) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.4.2) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.4.2) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.4.2) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.4.2) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.4.2) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.4.2) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.4.2) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.4.2) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.4.2) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.4.2) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.4.2) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.4.2) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.4.2) lib/action_dispatch/routing/route_set.rb:840:in `call'
railties (5.2.4.2) lib/rails/engine.rb:524:in `call'
railties (5.2.4.2) lib/rails/railtie.rb:190:in `public_send'
railties (5.2.4.2) lib/rails/railtie.rb:190:in `method_missing'
actionpack (5.2.4.2) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (5.2.4.2) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (5.2.4.2) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.4.2) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.4.2) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.4.2) lib/action_dispatch/routing/route_set.rb:840:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.2.2) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.2) lib/rack/etag.rb:27:in `call'
rack (2.2.2) lib/rack/conditional_get.rb:40:in `call'
rack (2.2.2) lib/rack/head.rb:12:in `call'
actionpack (5.2.4.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.2) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.2) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/cookies.rb:670:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.4.2) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.4.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
lograge (0.11.2) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
railties (5.2.4.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.4.2) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.4.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.4.2) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.4.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.2) lib/rack/method_override.rb:24:in `call'
rack (2.2.2) lib/rack/runtime.rb:22:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.2) lib/rack/sendfile.rb:110:in `call'
railties (5.2.4.2) lib/rails/engine.rb:524:in `call'
rack (2.2.2) lib/rack/urlmap.rb:74:in `block in call'
rack (2.2.2) lib/rack/urlmap.rb:58:in `each'
rack (2.2.2) lib/rack/urlmap.rb:58:in `call'
capybara (3.12.0) lib/capybara/server/middleware.rb:48:in `call'
puma (3.12.4) lib/puma/configuration.rb:227:in `call'
puma (3.12.4) lib/puma/server.rb:675:in `handle_request'
puma (3.12.4) lib/puma/server.rb:476:in `process_client'
puma (3.12.4) lib/puma/server.rb:334:in `block in run'
puma (3.12.4) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
  ```
</details>

**Comment by spaghetticode** [comment]
@rainerdema thanks for pointing this out. 

🤦 It's actually a leftover from a very early implementation of Stripe Intents using the stripe gem, starting from their tutorial:

<img width="778" alt="Screen Shot 2020-05-15 at 8 34 42 AM" src="https://user-images.githubusercontent.com/141220/82019269-36102300-9687-11ea-8768-3ea5fbb78662.png">

This needs to be removed, as the Payment Intents process is now based on ActiveMerchant.
